### ISSUE TITLE
XIST library

### ISSUE THREAD

**Issue by DongxinZhao** [ucsd-ccbb/mali-dual-crispr-pipeline#5]
Hi Amanda,

I have successfully re-run the MRV4 library this afternoon. However, when I tried another library XIST using the same command, some errors happened.  In the notebook, the html file of step 4 -count_combination didn't generate, although the ipynb file is fine. 

![image](https://cloud.githubusercontent.com/assets/27448832/25023241/f1bd1fa8-204d-11e7-9a91-dffc41de7ba8.png)

Could you please help to figure out what's going on? Thanks!

Dongxin

**Comment by AmandaBirmingham** [comment]
Hi, Dongxin,
The problem is that when the counting notebook runs, it finds an issue in the library file:
ValueError: sequence 'AGAAATAGACACACAAAGCA' associated with name '10498' but was already associated with name '10349' 

I have looked into the library file and can confirm that the probe sequence 'AGAAATAGACACACAAAGCA'  is definitely associated with both those different probe ids.  This is not allowed by the software because it determines probe identity by looking at the probe sequence found in the read; if more than one probe had the same sequence, the software would not be able to figure out which probe it should go with.

I believe that if you fix this issue in the library file, the error from the software will disappear.  

If time permits, I'll add extend the software to be able to validate a library file and find issues like this before the library file is actually used in the counting or scoring calls.
